# Generated by Django 4.1.5 on 2023-02-07 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningresult',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountlisteningresults', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readingresult',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountreadingresults', to=settings.AUTH_USER_MODEL),
        ),
    ]
