# Generated by Django 4.1.5 on 2023-01-30 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_course_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='account.course')),
            ],
        ),
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('audio', models.FileField(upload_to='audio/')),
                ('max_result', models.IntegerField(default=0)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listenings', to='account.homework')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('value', models.IntegerField(default=0)),
                ('listening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listeningquestions', to='account.listening')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('max_result', models.IntegerField(default=0)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='account.homework')),
            ],
        ),
        migrations.AlterField(
            model_name='unit',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='account.course'),
        ),
        migrations.CreateModel(
            name='ReadingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountreadingresult', to=settings.AUTH_USER_MODEL)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readingresults', to='account.reading')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=256)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readinganswers', to='account.reading')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountlisteningresult', to=settings.AUTH_USER_MODEL)),
                ('listening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listeningresults', to='account.listening')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=528)),
                ('is_true', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listeningquestionanswers', to='account.listeningquestion')),
            ],
        ),
    ]
